### ISSUE TITLE
Error executing 'postInstallation': Timeout: did not get to load all resources on this page

### ISSUE THREAD

**Issue by eanfs** [bitnami/bitnami-docker-orangehrm#28]
**Description**

Error executing 'postInstallation': Timeout: did not get to load all resources on this page
on mac os

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by davidbhlm-github** [comment]
Hi @eanfs ,

I tested using the docker-compose.yml from the repo and see no issues. Could you provide some more information that would allow us to reproduce this issue?

The issues section of the readme lists some of the information that you should attach to your issue report. Additionally let us know the docker platform in use (docker-engine on Linux, Docker for Windows, Docker for Mac, etc).

Regards
