### ISSUE TITLE
Can not login with default user/pass

### ISSUE THREAD

**Issue by tulu1688** [bitnami/bitnami-docker-orangehrm#30]
Hi,

I run the docker-compose.yml file and cant login with default user/pass

```
username: admin
password: OrangeHRM.12345
```

Can you fix

**Comment by juan131** [comment]
Hi @tulu1688 

I was unable to reproduce the issue. I used the default **docker-compose.yaml** with the default credentials:

```
username: admin
password: Bitnami.12345
```

And I could login and I was requested to change the default password:


![screen shot 2018-09-03 at 11 05 31](https://user-images.githubusercontent.com/6740773/44977813-58bcdf80-af69-11e8-8c21-8d87f48d22f5.png)

**Comment by juan131** [comment]
Oh! I just saw the issue. The README.md files states the default password is **OrangeHRM.12345** but it's **Bitnami.12345**. I'll fix it!! Thanks for reporting it.
