### ISSUE TITLE
Can not create new user

### ISSUE THREAD

**Issue by tulu1688** [bitnami/bitnami-docker-orangehrm#32]
Tried a lot of name format but cannot create new user.
The employee name fields always be "Invalid"

Attached images is the evidence
![orangehrm](https://user-images.githubusercontent.com/1001126/44995087-b08c3280-afcb-11e8-99f4-67586a4d6e52.png)

**Comment by beltran-rubo** [comment]
hi!

It is required to create an employee before creating an OranHRM user who can manage the application.

Once you create the Employee at "PIM" -> "Add Employee", you are able to select that user in the "User Management" tab.

<img width="694" alt="screen shot 2018-09-04 at 10 10 12" src="https://user-images.githubusercontent.com/3718440/45018747-fb896280-b02a-11e8-8ef3-433a3a5010c2.png">

I hope it helps
