### ISSUE TITLE
Container not loading

### ISSUE THREAD

**Issue by Lavardin** [bitnami/bitnami-docker-orangehrm#36]
My OrangeHRM container won't load after a reboot and when I check the logs it states:

Error postInstallation no SELECT 'country'

**Comment by Lavardin** [comment]
I'm using docker.

**Comment by carrodher** [comment]
When you said "reboot", what commands do you mean?

I tried using the latest image via `docker-compose` and tried the following "reboot" operations:
- `docker-compose start` ✅ 
- `docker-compose stop && docker-compose start` ✅ 
- `docker-compose down && docker-compose up` ✅ 

In the same way, can you execute `docker logs -f CONTAINER_ID` and paste here a few more lines surrounding the error? Are you using a specific tag or environment variables launching the image?

**Comment by Lavardin** [comment]
I pulled the latest version and tried it, but still the same. 

My container has a restart policy just in case my server reboots. Also the started occuring after using the commands docker stop and docker start.

This is from the logs.  


Welcome to the Bitnami orangehrm container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-orangehrm
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-orangehrm/issues

nami    INFO  Initializing apache
nami    INFO  apache successfully initialized
nami    INFO  Initializing php
nami    INFO  php successfully initialized
nami    INFO  Initializing mysql-client
nami    INFO  mysql-client successfully initialized
nami    INFO  Initializing orangehrm
orangeh INFO  Configuring permissions
orangeh INFO  Preparing webserver environment...
orangeh INFO  Creating the database...
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at 10.0.80.200:3306
mysql-c INFO  MySQL server listening and working at 10.0.80.200:3306
orangeh INFO  Passing wizard, please be patient
Error executing 'postInstallation': No SELECT matching 'country'

**Comment by Lavardin** [comment]
[
    {
        "Id": "0d926f1396d1535b1a4d647c92930264cd6a01d26da1a5d9eb0a66d91467ce7a",
        "Created": "2019-07-06T08:39:12.007041905Z",
        "Path": "/app-entrypoint.sh",
        "Args": [
            "httpd",
            "-f",
            "/opt/bitnami/apache/conf/httpd.conf",
            "-DFOREGROUND"
        ],
        "State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 137,
            "Error": "",
            "StartedAt": "2019-07-06T08:55:04.920802916Z",
            "FinishedAt": "2019-07-06T08:55:26.997820569Z"
        },
        "Image": "sha256:f586509c88a9d15b09848db08587e0b17846063db6057ff4f017b7b2035bbbdb",
        "ResolvConfPath": "/var/lib/docker/containers/0d926f1396d1535b1a4d647c92930264cd6a01d26da1a5d9eb0a66d91467ce7a/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/0d926f1396d1535b1a4d647c92930264cd6a01d26da1a5d9eb0a66d91467ce7a/hostname",
        "HostsPath": "/var/lib/docker/containers/0d926f1396d1535b1a4d647c92930264cd6a01d26da1a5d9eb0a66d91467ce7a/hosts",
        "LogPath": "/var/lib/docker/containers/0d926f1396d1535b1a4d647c92930264cd6a01d26da1a5d9eb0a66d91467ce7a/0d926f1396d1535b1a4d647c92930264cd6a01d26da1a5d9eb0a66d91467ce7a-json.log",
        "Name": "/orangehrm",
        "RestartCount": 30,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "docker-default",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/etc/localtime:/etc/localtime:ro"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "enp2s0f1.8",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "unless-stopped",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "shareable",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/9668ffdac80a57e89b111b35f7dbe345b7d99f2d3c2fb056feddda00076b8797-init/diff:/var/lib/docker/overlay2/5f6e4614e7418e3e0b96d8d66ed8e0591508a0bec364c2b074ba4ade4acb3d18/diff:/var/lib/docker/overlay2/e1b54f9e1e4fa10a570d873403264abc0196b31b412ce239f73e884c9adc8eaf/diff:/var/lib/docker/overlay2/f2ea60d49c136a71e31fdb1aeaa5b1b204d11417107f0d8ce2c692110c77def0/diff:/var/lib/docker/overlay2/4d0a3ab5429b9951157315dd47e2767bef179dff4a5723da33e079326108fced/diff:/var/lib/docker/overlay2/75d976854b4778d96fa1967be4aece91a3e645a51809bc5d47425c683722fda3/diff:/var/lib/docker/overlay2/8202bf251fbcdd37c92aa62206f56bffd02afc719d46436f268fa1ddccc0a88e/diff:/var/lib/docker/overlay2/bbd085b822283972f3f8fc756a003a5ce7ba94be9485a8209f9e4bc64a93b884/diff:/var/lib/docker/overlay2/b2f2d25ffb27fc0868b79ae2c84970fbd90f184535d2013c52b650093068d0dc/diff:/var/lib/docker/overlay2/bba8dc2243373fed5059b4d2c6420224bbdcbfab5fcdc5ba70f35cc8e1140e79/diff:/var/lib/docker/overlay2/647a297652a261d2f5fac53be6200bc9e1e5f182ea87d9519ce5f325566c3daa/diff:/var/lib/docker/overlay2/0211f0aa9d55f1989d304016cd9a32fa4dc5f271ce78061db29743cf47f2a4ef/diff:/var/lib/docker/overlay2/897ce40d68ff997a80397b1d21825af19b435a9f50febf40ef648fd74f3414db/diff:/var/lib/docker/overlay2/6f0390c56d88b720e70d1be815b2a75467ff0ff9c4c27a3f2779e3531d13bb3b/diff:/var/lib/docker/overlay2/e34b91a76c87068b25f4743062ccb6b79aea35c71ede798d95889521adff3efd/diff:/var/lib/docker/overlay2/f9463dfdcf61eaffc2cb206a05d278c333477b334f72a554348bab92e37facfa/diff:/var/lib/docker/overlay2/044d53e35387f24db0e027674d4d6cf5ca6e3430842bb1d7ed1eddc31b80f3f1/diff",
                "MergedDir": "/var/lib/docker/overlay2/9668ffdac80a57e89b111b35f7dbe345b7d99f2d3c2fb056feddda00076b8797/merged",
                "UpperDir": "/var/lib/docker/overlay2/9668ffdac80a57e89b111b35f7dbe345b7d99f2d3c2fb056feddda00076b8797/diff",
                "WorkDir": "/var/lib/docker/overlay2/9668ffdac80a57e89b111b35f7dbe345b7d99f2d3c2fb056feddda00076b8797/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/etc/localtime",
                "Destination": "/etc/localtime",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            },
            {
                "Type": "volume",
                "Name": "b15dabedcc3e511fbacaa31aadf67df920e5baa1d4fb9959ab22973af76d66ea",
                "Source": "/var/lib/docker/volumes/b15dabedcc3e511fbacaa31aadf67df920e5baa1d4fb9959ab22973af76d66ea/_data",
                "Destination": "/certs",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "orangehrm",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "443/tcp": {},
                "80/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "SMTP_PASSWORD=",
                "SMTP_USER=",
                "IMAGE_OS=debian-9",
                "ALLOW_EMPTY_PASSWORD=no",
                "MYSQL_CLIENT_CREATE_DATABASE_USER=",
                "ORANGEHRM_DATABASE_NAME=orangehrm",
                "ORANGEHRM_DATABASE_PASSWORD=PASSWORD",
                "SMTP_HOST=",
                "PATH=/opt/bitnami/apache/bin:/opt/bitnami/php/bin:/opt/bitnami/php/sbin:/opt/bitnami/mysql/bin:/opt/bitnami/nami/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "NAMI_VERSION=1.0.0-1",
                "TINI_VERSION=v0.13.2",
                "GOSU_VERSION=1.10",
                "MYSQL_CLIENT_CREATE_DATABASE_PRIVILEGES=ALL",
                "APACHE_SET_HTTPS_PORT=no",
                "MYSQL_CLIENT_CREATE_DATABASE_PASSWORD=",
                "ORANGEHRM_PASSWORD=PASSWORD",
                "MARIADB_HOST=10.0.80.200",
                "MARIADB_PORT_NUMBER=3306",
                "MARIADB_ROOT_PASSWORD=PASSWORD",
                "SMTP_PORT=",
                "SMTP_PROTOCOL=none",
                "GOSU_GPG_KEY=B42F6819007F00F88E364FD4036A9C25BF357DD4",
                "ORANGEHRM_DATABASE_USER=orangeusr",
                "TINI_GPG_KEY=595E85A6B1B4779EA4DAAEC70B588DFF0527A9B7",
                "BITNAMI_IMAGE_VERSION=4.3.2-0-debian-9-r3",
                "BITNAMI_APP_NAME=orangehrm",
                "ORANGEHRM_USERNAME=cshowalter",
                "GPG_KEY_SERVERS_LIST=ha.pool.sks-keyservers.net                          hkp://p80.pool.sks-keyservers.net:80                          keyserver.ubuntu.com                          hkp://keyserver.ubuntu.com:80                          pgp.mit.edu",
                "APACHE_HTTPS_PORT_NUMBER=",
                "APACHE_HTTP_PORT_NUMBER=",
                "APACHE_SET_HTTP_PORT=no",
                "MARIADB_ROOT_USER=lavardin",
                "MYSQL_CLIENT_CREATE_DATABASE_NAME="
            ],
            "Cmd": [
                "httpd",
                "-f",
                "/opt/bitnami/apache/conf/httpd.conf",
                "-DFOREGROUND"
            ],
            "ArgsEscaped": true,
            "Image": "bitnami/orangehrm:latest",
            "Volumes": {
                "/certs": {}
            },
            "WorkingDir": "",
            "Entrypoint": [
                "/app-entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": {
                "maintainer": "Bitnami <containers@bitnami.com>",
                "omv_docker_extra_args": "--net enp2s0f1.8 --ip 10.0.80.50"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "e41845bad56ea865809ca14fb9281184c6f335be707651fdaf6a4204151a5b77",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/e41845bad56e",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "enp2s0f1.8": {
                    "IPAMConfig": {
                        "IPv4Address": "10.0.80.50"
                    },
                    "Links": null,
                    "Aliases": [
                        "0d926f1396d1"
                    ],
                    "NetworkID": "c7208221fb240ccc67323696ca34ee84b5218905dd5e8590bf1436ca68bee23a",
                    "EndpointID": "",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "",
                    "DriverOpts": null
                }
            }
        }
    }
]

**Comment by Lavardin** [comment]
Looks like I have it up and running by starting the container with privileges. 

My next question is can I create certificates and cp them too /opt/bitnami/apache/conf/bitnami/certs replacing server.key and server.crt?

**Comment by rafariossaa** [comment]
Hi @Lavardin,
  Yes, you can copy the certs to that path.

Best regards,
