### ISSUE TITLE
Downgrade PHP Version

### ISSUE THREAD

**Issue by kangaroobar** [bitnami/bitnami-docker-orangehrm#39]
I am using the latest docker image to upgrade my orangehrm to version 4.9. However, orangehrm incompatible with PHP version 7.4. Is it possible Bitnami create a new docker image that compatible with orangehrm upgrade, or please guide me which PHP with checksum for me to build the correct docker image.

![image](https://user-images.githubusercontent.com/96571494/147219483-fe54a666-ada5-4464-a88e-e0ceb866f8c1.png)

**Comment by javsalgar** [comment]
Please, [note the Bitnami team is not actively monitoring GitHub Issues for this container](https://github.com/bitnami/charts/tree/master/bitnami/bitnami-docker-orangehrm#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

If you would like to contribute to this container chart by fixing a bug or adding a new feature feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
