### ISSUE TITLE
Cannot login with password set with ORANGEHRM_PASSWORD env variable

### ISSUE THREAD

**Issue by mtrp12** [bitnami/bitnami-docker-orangehrm#41]
**Description**

After downloading the docker-compose.yml file and adding the ORANGEHRM_PASSWORD environment variable under orangehrm section, I expected to login to admin account using that password. But it still only takes default Bitnami.12345 password.

**Steps to reproduce the issue:**

1. curl -sSL https://raw.githubusercontent.com/bitnami/bitnami-docker-orangehrm/master/docker-compose.yml > docker-compose.yml
2. add ORANGEHRM_PASSWORD
![image](https://user-images.githubusercontent.com/6695345/149759033-afa810e1-7fb8-4de6-b108-cbfa5319722b.png)

3. Try to login with new password at http://localhost:80

**Describe the results you received:**

![image](https://user-images.githubusercontent.com/6695345/149759282-9892981c-b2a1-4e27-be25-8ee2136afc8c.png)

**Describe the results you expected:**

Successful login.

**Additional information you deem important (e.g. issue happens only occasionally, environment details, etc.):**

I can only login with Bitnami.12345 even after setting the env variable.

**Comment by juan131** [comment]
Hi @mtrp12 

Please, [note the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-orangehrm#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.
If you would like to contribute to this container image by fixing a bug or adding a new feature feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by mtrp12** [comment]
Solved. Needed to remove the volumes from the first `docker-compose up`
